### PR TITLE
Class IncludeInReportAttribute to set if add or not the property on t…

### PR DESCRIPTION
**Pull request by rogerospina**
Hi @fingers10 this are the changes that I was talking about. If you see that this is not need, it's Ok, and we would close the "issue". =)

### CODE REVIEW

**Comment by fingers10** [comment]
Hey @rogerospina, Sorry for the delayed response. I was reviewing your PR yesterday. Did you checked your PR with Nested Models? Was it working?

**Comment by rogerospina** [comment]
Hi, @fingers10 Don't worry, It's ok. No, I didn't test that case, But I think I wouldn't be a problem, because this attribute it'd be for a specific property.

**Comment by fingers10** [comment]
@rogerospina  Thanks for the PR. I'll work and expand on this further.

**Comment by rogerospina** [comment]
@fingers10 Thanks to You.

**Pull request merged**
